### ISSUE TITLE
SecurityException - Too many alarms registered

### ISSUE THREAD

**Issue by mobiRic** [transistorsoft/background-geolocation-lt#110]
We have observed the following `SecurityException` crash happening on a customer device multiple times over the last 12 hour period, suggesting that the SDK is setting too many alarms (possibly as part of a keep-alive strategy, or for battery saving?).

- `java.lang.SecurityException: !@Too many alarms (500) registered from uid 10161`

## Your Environment
* Plugin version: 3.1.7 (363)
* Platform: Android
* OS version: Android 8.1.0
* Device manufacturer / model: Samsung Galaxy Tab Active 2 (Model: SM-T397U)
* Plugin config

```
        TSConfig.getInstance(context).updateWithBuilder()
                .setDebug(false)
                .setLogLevel(1)
                .setLocationUpdateInterval(5000L)
                .setFastestLocationUpdateInterval(5000L)
                .setForegroundService(true)
                .setStopOnTerminate(false)
                .setStartOnBoot(true)
                .setEnableHeadless(false)
                .setNotification(notification)
                .setAutoSync(true)
                .setAutoSyncThreshold(0)
                .setBatchSync(true)
                .setMaxBatchSize(100)
                .commit();
```

## Expected Behavior
`TSScheduleManager.oneShot(String, long, boolean)` should not cause the app to crash

## Actual Behavior
App crashes with the following `SecurityException` and stack trace.

```
java.lang.RuntimeException: Unable to start service com.transistorsoft.locationmanager.service.TrackingService@fb781a2 with Intent { act=STOP_TIMEOUT cmp=com.rapiddeploy/com.transistorsoft.locationmanager.service.TrackingService }: java.lang.SecurityException: !@Too many alarms (500) registered from uid 10161
  at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3710)
  at android.app.ActivityThread.-wrap22(ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1827)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:164)
  at android.app.ActivityThread.main(ActivityThread.java:7000)
  at java.lang.reflect.Method.invoke(Method.java:-2)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

  Caused by: java.lang.SecurityException: !@Too many alarms (500) registered from uid 10161
    at android.os.Parcel.readException(Parcel.java:2029)
    at android.os.Parcel.readException(Parcel.java:1975)
    at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:217)
    at android.app.AlarmManager.setImpl(AlarmManager.java:697)
    at android.app.AlarmManager.setExactAndAllowWhileIdle(AlarmManager.java:902)
    at com.transistorsoft.locationmanager.scheduler.TSScheduleManager.oneShot(TSScheduleManager.java:343)
    at com.transistorsoft.locationmanager.service.TrackingService.a(TrackingService.java:156)
    at com.transistorsoft.locationmanager.service.TrackingService.onStartCommand(TrackingService.java:135)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3693)
    at android.app.ActivityThread.-wrap22(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1827)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:7000)
    at java.lang.reflect.Method.invoke(Method.java:-2)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

## Steps to Reproduce
Unknown - Stack trace suggests this is happening on startup.

## Context
Unknown

## Debug logs
Unknown device logs - this is the first occurrence we have seen of this crash and it on a customer's device.

**Comment by mobiRic** [comment]
For what it is worth, we are not using FCM in the app, which was previously known to cause this exception.
