### ISSUE TITLE
Crash when running Android Version 31 and above

### ISSUE THREAD

**Issue by Anastasiael** [transistorsoft/background-geolocation-lt#120]
## Your Environment
* Plugin version: 1.4.0
* Platform: Android
* OS version: 33
* Device manufacturer / model: Galaxy & Pixel

For the module to work with Android 12 I made the following additions to the AndroidManifest of the 3.1.7 (added android:exported, permissions and foregroundServiceType where needed) 
```
<?xml version="1.0" encoding="UTF-8"?><manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.transistorsoft.tslocationmanager" android:versionCode="363" android:versionName="3.1.7">
    <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="29"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.GET_TASKS"/>
    <!-- device-specific permissions for DeviceSettings methods -->
    <uses-permission android:name="oppo.permission.OPPO_COMPONENT_SAFE"/>
    <uses-permission android:name="com.huawei.permission.external_app_settings.USE_COMPONENT"/>
    <uses-feature android:name="android.hardware.location.gps" android:required="false"/>
    <application>
        <activity android:name="com.transistorsoft.locationmanager.activity.TSLocationManagerActivity" android:excludeFromRecents="true" android:launchMode="singleInstance" android:theme="@style/AppTheme.Transparent"/>
        <service android:name="com.transistorsoft.locationmanager.service.TrackingService" android:foregroundServiceType="location"/>
        <service android:name="com.transistorsoft.locationmanager.service.LocationRequestService" android:foregroundServiceType="location"/>
        <service android:name="com.transistorsoft.locationmanager.service.HeartbeatService"/>
        <service android:name="com.transistorsoft.locationmanager.service.ActivityRecognitionService"/>
        <service android:name="com.transistorsoft.locationmanager.service.GeofencingService"/>
        <service android:name="com.transistorsoft.locationmanager.service.BackgroundTaskService"/>
        <receiver android:name="com.transistorsoft.locationmanager.scheduler.ScheduleAlarmReceiver" android:exported="false"/>
        <service android:name="com.transistorsoft.locationmanager.scheduler.ScheduleService"/>
        <service android:name="com.transistorsoft.locationmanager.scheduler.ScheduleJobService" android:exported="true" android:permission="android.permission.BIND_JOB_SERVICE"/>
        <receiver android:name="com.transistorsoft.locationmanager.BootReceiver" android:enabled="true" android:exported="false" android:permission="android.permission.RECEIVE_BOOT_COMPLETED">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
            </intent-filter>
        </receiver>
        <provider android:name="com.transistorsoft.locationmanager.util.LogFileProvider" android:authorities="${applicationId}.tslocationmanager.fileprovider" android:exported="false" android:grantUriPermissions="true">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/tslocationmanager_file_provider_path"/>
        </provider>
    </application>
</manifest>
```

## Expected Behavior
App should start tracking with no problem.

## Actual Behavior
When the app tries to start locating the following crash occurs.
```
Fatal Exception: java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
       at android.app.PendingIntent.checkFlags(PendingIntent.java:408)
       at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:767)
       at android.app.PendingIntent.getForegroundService(PendingIntent.java:759)
       at com.transistorsoft.locationmanager.service.ActivityRecognitionService.a(:25)
       at com.transistorsoft.locationmanager.service.ActivityRecognitionService.b(:48)
       at com.transistorsoft.locationmanager.service.TrackingService.a(:30)
       at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$w0.run(:238)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```

## Steps to Reproduce

1. Run it on a device with API over 31. 
2. Start tracking.

**Comment by christocracy** [comment]
This library is no longer supported for pure native apps.  Only cross platform frameworks Cordova, Capacitor, React Native and Flutter are supported.
