### ISSUE TITLE
Problem with license and the foreground notification acting up.

### ISSUE THREAD

**Issue by zend10** [transistorsoft/background-geolocation-lt#55]
Hello, I have several problems here.

First, it works well on pixel emulator from android studio. However, problems happened when I tried it on several Xiaomi devices I was working with, ranging from Lollipop to Pie.

Here is the exception it shows:
```
E/EventBus: Could not dispatch event: class com.transistorsoft.locationmanager.location.WatchPositionResult to subscribing class class com.transistorsoft.locationmanager.location.TSLocationManager
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.containsKey(java.lang.String)' on a null object reference
        at com.transistorsoft.locationmanager.location.TSLocationManager.b(Unknown Source:30)
        at com.transistorsoft.locationmanager.location.TSLocationManager.buildTSLocation(Unknown Source:10)
        at com.transistorsoft.locationmanager.location.TSLocationManager.onWatchPositionResult(Unknown Source:23)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
        at org.greenrobot.eventbus.BackgroundPoster.run(BackgroundPoster.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.SubscriberExceptionEvent
```

And I noticed that there's actually version release-3.0.0 so I upgraded to that. I initially used version 0.2.0 from Release page.

But now when I run it, it shows me a toast saying "LICENSE VALIDATION FAILURE". Also, the notification shows up and go continuously while I'm on foreground, making my app lagging. I've even removed watch location code and it's still happening.

What might the problem there?
What's the matter with my license?
Why won't it work in version 0.2.0 from Release page?
What causes that notification problem?

Thank you.

This is my config:
```
config.updateWithBuilder()
            .setDebug(false)
            .setLogLevel(5)
            .setDesiredAccuracy(LocationRequest.PRIORITY_HIGH_ACCURACY)
            .setDistanceFilter(0F)
            .setLocationUpdateInterval(5000L)
            .setFastestLocationUpdateInterval(3000L)
            .setDeferTime(0L)
            .setAllowIdenticalLocations(false)
            .setStationaryRadius(25)
            .setDisableElasticity(true)
            .setStopAfterElapsedMinutes(-1)
            .setStopOnStationary(false)
            .setUrl(Constant.SOCKET_URL + "locationsv3")
            .setMethod("POST")
            .setParams(param)
            .setHttpRootProperty("data")
            .setBatchSync(true)
            .setMaxBatchSize(10) 
            .setAutoSync(true)
            .setAutoSyncThreshold(0)
            .setMaxDaysToPersist(7)
            .setMaxRecordsToPersist(-1)
            .setLocationsOrderDirection("ASC")
            .setStopOnTerminate(false)
            .setStartOnBoot(true)
            .setHeartbeatInterval(30)
            .setForegroundService(true)
            .commit()
```

If I'm using it wrong, please guide me the correct way. Thank you.

**Comment by zend10** [comment]
Okay, it's actually working as intended when I don't use the watchLocation. Kind of unstable in Xiaomi device but I don't think it can be helped. Still, you probably should look into it and find out why watchLocation causes exception on some device.

The license problem was I didn't notice there was actually one year limit to get the latest update.

My problem is solved. You are free to close the issue. Thanks for the cool lib.
