### ISSUE TITLE
Uncaught Exception: Failed resolution of: Ljava/time/ZonedDateTime

### ISSUE THREAD

**Issue by kosiarska** [transistorsoft/background-geolocation-lt#61]
This happens every time I start location tracking.

```
2019-08-28 11:48:21.474 26378-26565/com.droids.in10.qa E/TSLocationManager: [c.t.l.a.BackgroundGeolocation$e uncaughtException] 
      ‼️  Uncaught Exception: Failed resolution of: Ljava/time/ZonedDateTime;
    {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"autoSync":true,"autoSyncThreshold":0,"batchSync":false,"debug":true,"deferTime":0,"desiredAccuracy":100,"desiredOdometerAccuracy":100,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableStopDetection":false,"distanceFilter":10,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"extras":{},"fastestLocationUpdateInterval":-1,"forceReloadOnBoot":false,"forceReloadOnGeofence":false,"forceReloadOnHeartbeat":false,"forceReloadOnLocationChange":false,"forceReloadOnMotionChange":false,"forceReloadOnSchedule":false,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationTemplate":"","locationTimeout":60,"locationUpdateInterval":1000,"locationsOrderDirection":"ASC","logLevel":5,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","smallIcon":"","largeIcon":"","priority":0,"strings":{},"actions":[]},"params":{"device":{"uuid":"5f3512640b1eea21","model":"LG-M250","platform":"Android","manufacturer":"LGE","version":"7.0","framework":"Native"}},"persist":true,"persistMode":2,"schedule":["2019-08-28-11:48 2019-08-28-11:57"],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":true,"stationaryRadius":30,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":5,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"http:\/\/tracker.transistorsoft.com\/locations\/kosiarska","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":true,"trackingMode":1,"odometer":206.7760467529297,"isFirstBoot":false}
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZonedDateTime;
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:241)
        at com.google.maps.internal.OkHttpPendingResult.onResponse(OkHttpPendingResult.java:207)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.ZonedDateTime" on path: DexPathList[[zip file "/data/app/com.droids.in10.qa-1/base.apk"],nativeLibraryDirectories=[/data/app/com.droids.in10.qa-1/lib/arm, /data/app/com.droids.in10.qa-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    	... 6 common frames omitted
```

## Your Environment
* Plugin version: 3.0.26
* Platform: Android
* OS version: 9 
* Device manufacturer / model: LG K10

**Comment by kosiarska** [comment]
Multi dex is already enabled in the project.

**Comment by kosiarska** [comment]
Ok, I''ll remember not to ignore issue template next time. Problem was in a google maps services library. So it's not transistor library fault.
