### ISSUE TITLE
NullPointerException: Attempt to read from field 'double android.location.Location.mLatitude' on a null object reference

### ISSUE THREAD

**Issue by ngoni** [transistorsoft/background-geolocation-lt#69]
## Your Environment
* Plugin version: 1.0.4
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Samsung SM-A720F
* Plugin config

        final TSConfig config = TSConfig.getInstance(context);

        // Configure Foreground Service notification
        final TSConfig.Notification notification = buildNotification();

        // build custom fields for the API
        JSONObject params = buildHttpParams();

        // Configure the SDK:
        config.updateWithBuilder()
                .setDebug(false)
                .setLogLevel(3)
                .setLocationUpdateInterval(5000L)
                .setFastestLocationUpdateInterval(5000L)
                .setForegroundService(true)
                .setStopOnTerminate(false)
                .setStartOnBoot(true)
                .setEnableHeadless(false)
                .setNotification(notification)
                .setAutoSync(true)
                .setAutoSyncThreshold(0)
                .setBatchSync(true)
                .setMaxBatchSize(100)
                .setParams(params)
                .commit();

## Context

The application crashed in production, I don't have data on how to replicate the crash.

## Debug logs

java.lang.RuntimeException: Unable to start service com.transistorsoft.locationmanager.service.TrackingService@abcee74 with Intent { cmp=com.rapiddeploy.mobile.beta/com.transistorsoft.locationmanager.service.TrackingService (has extras) }: java.lang.NullPointerException: Attempt to read from field 'double android.location.Location.mLatitude' on a null object reference
  at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3696)
  at android.app.ActivityThread.-wrap21(ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
  at android.os.Handler.dispatchMessage(Handler.java:105)
  at android.os.Looper.loop(Looper.java:164)
  at android.app.ActivityThread.main(ActivityThread.java:6944)
  at java.lang.reflect.Method.invoke(Method.java:-2)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
  Caused by: java.lang.NullPointerException: Attempt to read from field 'double android.location.Location.mLatitude' on a null object reference
    at android.location.Location.distanceTo(Location.java:482)
    at com.transistorsoft.locationmanager.service.TrackingService.a(TrackingService.java:315)
    at com.transistorsoft.locationmanager.service.TrackingService.onStartCommand(TrackingService.java:190)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3679)
    at android.app.ActivityThread.-wrap21(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6944)
    at java.lang.reflect.Method.invoke(Method.java:-2)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by christocracy** [comment]
Try latest 1.1.0 in master.

**Comment by ngoni** [comment]
Will give it a go. Thanks
