### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference

### ISSUE THREAD

**Issue by ngoni** [transistorsoft/background-geolocation-lt#74]
## Your Environment
* Plugin version: 1.0.4
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: Blackview BV9500
* Plugin config

```
  final TSConfig config = TSConfig.getInstance(context);

  // Configure Foreground Service notification
  final TSConfig.Notification notification = buildNotification();

  // build custom fields for the API
  JSONObject params = buildHttpParams();

  // Configure the SDK:
  config.updateWithBuilder()
          .setDebug(false)
          .setLogLevel(3)
          .setLocationUpdateInterval(5000L)
          .setFastestLocationUpdateInterval(5000L)
          .setForegroundService(true)
          .setStopOnTerminate(false)
          .setStartOnBoot(true)
          .setEnableHeadless(false)
          .setNotification(notification)
          .setAutoSync(true)
          .setAutoSyncThreshold(0)
          .setBatchSync(true)
          .setMaxBatchSize(100)
          .setParams(params)
          .commit();

```

## Context

The application crashed in production, I don't have data on how to replicate the crash.

## Debug logs

```
java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
  at com.transistorsoft.locationmanager.location.TSLocationManager$3.a(TSLocationManager.java:4)
  at com.transistorsoft.locationmanager.location.TSLocationManager$3.compare(TSLocationManager.java:4)
  at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
  at java.util.TimSort.sort(TimSort.java:220)
  at java.util.Arrays.sort(Arrays.java:1498)
  at java.util.ArrayList.sort(ArrayList.java:1470)
  at java.util.Collections.sort(Collections.java:201)
  at com.transistorsoft.locationmanager.location.TSLocationManager.calculateMedianAccuracy(TSLocationManager.java:37)
  at com.transistorsoft.locationmanager.location.TSLocationManager.setLastLocation(TSLocationManager.java:31)
  at com.transistorsoft.locationmanager.location.TSLocationManager.buildTSLocation(TSLocationManager.java:10)
  at com.transistorsoft.locationmanager.location.TSLocationManager.onSingleLocationResult(TSLocationManager.java:353)
  at com.transistorsoft.locationmanager.service.LocationRequestService.a(LocationRequestService.java:352)
  at com.transistorsoft.locationmanager.service.LocationRequestService.a(LocationRequestService.java)
  at com.transistorsoft.locationmanager.service.LocationRequestService$a.run(LocationRequestService.java:18)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
  at java.lang.Thread.run(Thread.java:764)
```

**Comment by ngoni** [comment]
@christocracy any feedback on this yet?

**Comment by christocracy** [comment]
Have you installed latest version tagged last week?  If you *Watch* this repo, you’ll be notified of commits.

**Comment by ngoni** [comment]
Thanks. I've started watching the repo :-)
