### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'float com.google.android.gms.location.LocationRequest.W()' on a null object reference

### ISSUE THREAD

**Issue by ngoni** [transistorsoft/background-geolocation-lt#75]
## Your Environment
* Plugin version: 1.0.4
* Platform: Android
* OS version: Android 10
* Device manufacturer / model: Google Pixel 3
* Plugin config

```
final TSConfig config = TSConfig.getInstance(context);

  // Configure Foreground Service notification
  final TSConfig.Notification notification = buildNotification();

  // build custom fields for the API
  JSONObject params = buildHttpParams();

  // Configure the SDK:
  config.updateWithBuilder()
          .setDebug(false)
          .setLogLevel(3)
          .setLocationUpdateInterval(5000L)
          .setFastestLocationUpdateInterval(5000L)
          .setForegroundService(true)
          .setStopOnTerminate(false)
          .setStartOnBoot(true)
          .setEnableHeadless(false)
          .setNotification(notification)
          .setAutoSync(true)
          .setAutoSyncThreshold(0)
          .setBatchSync(true)
          .setMaxBatchSize(100)
          .setParams(params)
          .commit();
```

## Context

The application crashed in production, I don't have data on how to replicate the crash.

## Debug logs

```
java.lang.NullPointerException: Attempt to invoke virtual method 'float com.google.android.gms.location.LocationRequest.W()' on a null object reference
  at com.transistorsoft.locationmanager.location.TSLocationManager.onLocationResult(TSLocationManager.java:94)
  at com.transistorsoft.locationmanager.service.TrackingService$1.run(TrackingService.java:4)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  at java.lang.Thread.run(Thread.java:919)
```

**Comment by ngoni** [comment]
@christocracy I will email you the lib logs separatelyl.

**Comment by christocracy** [comment]
Try latest version merged to master.
